# Generated by Django 4.1.1 on 2022-09-24 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=250)),
                ('surnames', models.CharField(max_length=250)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('heartrate', models.IntegerField(blank=True, help_text='Frecuencia Cardiaca(Heart Rate) medida en BPM(Beats per minute)/Pulsaciones por minuto', null=True)),
                ('bloodoxygensaturation', models.IntegerField(blank=True, help_text='Saturación de Oxígeno en Sangre', null=True)),
                ('stresslevel', models.CharField(choices=[('l', 'Low'), ('m', 'Moderate'), ('h', 'High'), ('e', 'Extreme')], default='l', help_text='Nivel de estrés', max_length=5)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
